### ISSUE TITLE
Log-in and sign-in

### ISSUE THREAD

**Issue by Lenitsag** [shug0/check-dat#1]
For now, I can't tell the difference when I'm signing in for the first time, and when i'm logging back. It would be nice to show more informations about this to the user, what do you think ? 
Maybe with a message like "You already have an account bound to this Twitter, so we logged you in" or something like this idk.

**Comment by shug0** [comment]
Hello @Lenitsag, thanks for your interest. 

Curently the app only allow login with Google or Twitter, when you log for the first time a user is created for your account.

There is no real "signin" cause it's always a login in fact. 
A "login" button is more relevant cause it's what it's done. In the future the app will have a signup part with a external provider but when you will be able to choose a pseudo for example.

**Comment by shug0** [comment]
The use of email + password firebase authentification method resolve this issue by giving to the user a *Login* and *Signup* screen.
